version: "3.3"

services:

  scrabble:
    image: tgmgroup/docker-scrabble
    container_name: scrabble
    restart: always
    volumes:
      - type: bind
        source: /data/config.json
        target: /app/config.json
        read_only: true
    networks:
      - web
    ports:
      - "9093:9093"

networks:
  web:
    external: true
