name: Crossword Game

# Configure the "docker" workflow to run every time a change
# is pushed
on: [push]

env:
  # Container registry domain (Github packages)
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build jsdoc code documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./js
          recurse: true
          config_file: ./js/build/jsdoc_config.json
          output_dir: ./doc
